import type { NextPage } from 'next';
import { useState, useEffect } from "react";
import Head from 'next/head';
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SearchBar from '../components/SearchBar';
import useViewport from "../hooks/useViewport";
import styles from "../styles/Blog.module.scss";
import PostCard from '../components/PostCard';
import getPosts from '../helpers/getPosts';
import dateToString from '../helpers/dateToString';
import sortByRecent from '../helpers/sortByRecent';
import getCategories from '../helpers/getCategories';

type Posts = {
    slug: string;
    data: {
      title: string;
      date: string;
      description: string;
      category: string;
    }
  }
  
  type BlogProps = {
    posts: Posts[];
    categories: string[];
  }

const Blog = ({ posts, categories }: BlogProps) => {

    const {isMobile, isTablet, isDesktop} = useViewport();
    const [input, setInput] = useState("");

    posts = sortByRecent(posts);
    const matches = posts.filter(element => {
        if (element.data.title.toLowerCase().includes(input) || element.data.description.toLowerCase().includes(input) || element.data.category.toLowerCase().includes(input)) {
            return true;
        }
    })

    console.log(matches);

    return (
        <div className={styles.container}>
            <Head>
                <title>Blog | Ben Asokanthan</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar isDesktop={isDesktop} />
                <div className={styles.main}>
                    <div className={styles.search}>
                        <label className={styles.label}>Blog</label>
                        <br />
                        <SearchBar input={input} setInput={setInput} />
                        {matches.map((post) => (
                            <PostCard
                                key={post.slug}
                                transparent
                                title={post.data.title}
                                link={`/blog/${post.slug}`}
                                category={post.data.category}
                                date={dateToString(new Date(post.data.date))}
                            >
                                {post.data.description}
                            </PostCard>
                        ))}
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}

export default Blog;

export const getStaticProps = () => {
  const posts = getPosts();
  const categories = getCategories();

  return {
    props: {
      posts,
      categories,
    },
  };
};