import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import PostCard from '../components/PostCard';
import Footer from '../components/Footer';
import useViewport from '../hooks/useViewport';

const Home: NextPage = () => {

  const categories: String[] = ["React", "Animation", "CSS", "Git", "DSA"];

  const {isMobile, isTablet, isDesktop} = useViewport();

  return (
    <div className={styles.container}>
      <Head>
        <title>Ben Asokanthan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar isDesktop={isDesktop} />
        <Hero isDesktop={isDesktop} />
        <div className={styles.recent}>
          <h2>RECENTLY PUBLISHED</h2>
          <div className={styles.recentPosts}>
            <PostCard transparent title="You Don't Need a UI Framework" link="" >As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way.</PostCard>
            <PostCard transparent title="You Don't Need a UI Framework" link="" >As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way.</PostCard>
            <PostCard transparent title="You Don't Need a UI Framework" link="" >As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way.</PostCard>
            <PostCard transparent title="You Don't Need a UI Framework" link="" >As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way.</PostCard>
          </div>
          <h2>TOP CATEGORIES</h2>
          <div className={styles.categories}>
            {categories.map((category, index) => <a key={index} className={styles.category} href="">{category}</a>)}
          </div>
        </div>
      </main>

      <Footer />

    </div>
  )
}

export default Home
