import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Navbar from '../components/Navbar';
import Hero from '../components/Hero';
import PostCard from '../components/PostCard';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar recent="" posts="" resume="./basokant_resume_april2022.pdf" />
        <Hero />
        <div className={styles.recent}>
          <PostCard transparent title="You Don't Need a UI Framework" link="" description="As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way."></PostCard>
          <PostCard transparent title="You Don't Need a UI Framework" link="" description="As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way."></PostCard>
          <PostCard transparent title="You Don't Need a UI Framework" link="" description="As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way."></PostCard>
          <PostCard transparent title="You Don't Need a UI Framework" link="" description="As developers, it can be tempting to grab a pre-styled UI framework like Material UI or Bootstrap. Seems like a great way to outsource design and save a bunch of time, right? In my experience, this is an unrealistic expectation, and things don't quite work out that way."></PostCard>
        </div>
      </main>

    </div>
  )
}

export default Home
