import type { NextPage } from 'next';
import { useState, useEffect } from "react";
import Head from 'next/head';
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SearchBar from '../components/SearchBar';
import useViewport from "../hooks/useViewport";
import styles from "../styles/Posts.module.scss";

const Posts: NextPage = () => {

    const {isMobile, isTablet, isDesktop} = useViewport();
    const [input, setInput] = useState("");

    return (
        <div className={styles.container}>
            <Head>
                <title>Ben Asokanthan | Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Navbar isDesktop={isDesktop} />
                <div className={styles.main}>
                    <div>
                        <label className={styles.label}>Blog</label>
                        <br />
                        <SearchBar input={input} setInput={setInput} />
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    )

}

export default Posts;